Newer Docker images must already have a group/user of 1000 nowadays; So we'll go with 1001
The error I was getting when building the image was:

```
 => ERROR [stage-1 4/4] RUN groupadd --gid 1000 nonroot     && useradd --no-log-init --uid 1000 --gid 1000 --create-home nonroot                                                                                0.1s
------
 > [stage-1 4/4] RUN groupadd --gid 1000 nonroot     && useradd --no-log-init --uid 1000 --gid 1000 --create-home nonroot:
0.092 groupadd: GID '1000' already exists
------
Dockerfile:34
--------------------
  33 |     ARG USER_GID=${USER_UID}
  34 | >>> RUN groupadd --gid ${USER_GID} ${USERNAME} \
  35 | >>>     && useradd --no-log-init --uid ${USER_UID} --gid ${USER_GID} --create-home ${USERNAME}
  36 |     # Switch to the lower privileged user
--------------------
ERROR: failed to solve: process "/bin/sh -c groupadd --gid ${USER_GID} ${USERNAME}     && useradd --no-log-init --uid ${USER_UID} --gid ${USER_GID} --create-home ${USERNAME}" did not complete successfully: exit code: 4
```